# Generated by Django 4.0.3 on 2022-04-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
